### ISSUE TITLE
Is there any way to change the serving size?

### ISSUE THREAD

**Issue by linking** [globalfoodbook/nutrition-facts-label#5]
Hello, wonderful plugin. Is there any way to change the serving size?

Thank you

**Comment by ikennaokpala** [comment]
Sorry for the delay.. I have just seen this issue.. 

Are you referring to the "Serving Size" below the textbox in the Nutrition Label

See image below.

<img width="343" alt="screen shot 2016-02-22 at 12 38 50" src="https://cloud.githubusercontent.com/assets/84896/13218469/b6ea7d96-d961-11e5-9289-cfa635d5eac8.png">

At the moment it is not always updated.. whilst increasing the value of the "Serving Size" text-box above it.. thanks for spotting it..
